提交审核扩展 “简单积木” 扩展
Gandi-IDE/custom-extension pull request #105
Opened 2023-08-18 06:31 UTC by chaindisafho

扩展文件在 Easy 文件夹下的 Easy.js
共创用户名：JackGu

2023-08-18 06:52 UTC, sylarhcn commented
你这不是 gandi 格式的啊？搬运的 tw 的扩张吗？

2023-08-18 07:23 UTC, chaindisafho commented
不是搬运的
自己写的
我用的是默认格式的qwq

2023-08-18 07:23 UTC, chaindisafho commented
不是说可以用老版本的吗？

2023-08-18 07:46 UTC, DannyDevPro commented
你这也不是旧模板的格式啊 l10n都丢了

2023-08-18 07:47 UTC, yuen619 commented
还是你牛逼 66666

2023-08-18 07:49 UTC, DannyDevPro commented
![image](https://github.com/Gandi-IDE/custom-extension/assets/105956898/92c77189-badb-4022-9680-641246ead150)

2023-08-18 07:50 UTC, yuen619 commented
借鉴了多少arkosExt和便利积木啊（doge）

2023-08-18 08:57 UTC, chaindisafho commented
我没借鉴，你们自己看代码，没有一样的代码

2023-08-18 08:57 UTC, chaindisafho commented
所以能过审吗？

2023-08-18 08:59 UTC, chaindisafho commented
如果格式不对我去改
但是能不能给我个地方测试
因为改成Gandi格式后没法在TW里测试

2023-08-18 09:00 UTC, chaindisafho commented
@DannyDevPro 
问一下，l10n是啥？

2023-08-18 09:18 UTC, chaindisafho commented
请问有人能告诉我，示例的gandi代码的这段是干啥的吗？
![image](https://github.com/Gandi-IDE/custom-extension/assets/86557964/1374f699-ebb5-4c2a-8777-a813d5f81dee)

2023-08-19 07:27 UTC, chaindisafho commented
谁能回答我啊QAQ

2023-08-26 13:56 UTC, DannyDevPro commented
阿哲。。。 真的建议您去百度【如何编写sc扩展 以了解l10n是个神马东西】以了解l10n是个神马东西

2023-08-26 13:56 UTC, DannyDevPro commented
> 如果格式不对我去改 但是能不能给我个地方测试 因为改成Gandi格式后没法在TW里测试

readme都写了

2023-08-28 07:48 UTC, sylarhcn commented
> 

这是用于提供在 gandi 扩展库的目录信息的。必填项目

2023-08-28 07:50 UTC, sylarhcn requested changes
缺少积木的翻译。你可以使用 tw 的翻译模式，也可以参考本仓库中其他已合并的扩展的翻译方式。
总之，就是需要翻译。
tw 的翻译模式将在晚些时候支持

2023-08-28 11:01 UTC, little-starts commented
> 请问有人能告诉我，示例的gandi代码的这段是干啥的吗？
> ![image](https://github.com/Gandi-IDE/custom-extension/assets/86557964/1374f699-ebb5-4c2a-8777-a813d5f81dee)

注册拓展

2023-09-26 06:51 UTC, kukemc commented
建议 提交一些较高质量的扩展，此扩展的绝大部分功能社区已有扩展实现，没必要在搞一个扩展。
此扩展几乎是有90%的功能都是社区扩展已实现的

2023-09-27 08:50 UTC, sylarhcn commented
已经支持 tw 的翻译，你添加翻译后就可以通过。

功能相似的积木扩展也可以上线，但是我建议是不要重复在造轮子，这是只是建议，不是要求。

2024-02-27 06:17 UTC, sylarhcn commented on Easy/Easy.js
> +        id: 'easy',
id 请加上你的自己的前缀，避免使用过于简单的 id ，导致和其他扩展重复

2024-02-27 06:18 UTC, sylarhcn commented on Easy/Easy.js
> +        name: '简单积木',
扩展名字尽量切合扩展积木实际提供的功能。
所以我觉得“简单积木”这个名字过于笼统了，对于你提供的积木来说。可以更明确一点

2024-02-27 09:19 UTC, fath11 commented
> Functionally similar block expansions can also be launched, but my advice is not to repeat the wheel building, this is only a recommendation, not a requirement.

We shouldn't let those get launched. Currently, Gandi IDE has **three** alternatives to temporary variables, and none works with the other. On top of that, extensions that can do so much better with temp vars like Gandi Pure Math also don't support any of those temp vars and implementing support for all of them is tedious; I pretty much memorized all the blocks in every extension and still get overwhelmed with which one to use. Beginners are just going to be more confused.

2024-02-27 10:23 UTC, closed without merging