添加 CloudMusic 扩展
Gandi-IDE/custom-extension pull request #112
Opened 2023-09-02 07:06 UTC by SIPC

2023-09-02 07:23 UTC, kukemc commented
yes！is 歪瑞 good

2023-09-02 12:09 UTC, 10-cookies commented
牛逼

2023-09-03 15:58 UTC, little-starts commented
你这个不写英文不好过审啊，因为拓展会同步部署到国际版，还是在l10n加个英文吧？

2023-09-04 03:02 UTC, sylarhcn requested changes
请修改中文的 function name 为英文吧。

除了用于显示 l10n 语言，不要用中文编程吧。

2023-09-04 03:05 UTC, sylarhcn requested changes
请修改中文的 function name 为英文吧。

除了用于显示 l10n 语言，不要用中文编程吧。

2023-09-04 03:13 UTC, sylarhcn commented on sipc.ink/CloudMusic/CloudMusic.js
> +              reject(new Error('无法获取电台信息'));
错误建议也添加翻译。和积木中的翻译写法一样

2023-09-04 03:15 UTC, sylarhcn commented on sipc.ink/CloudMusic/CloudMusic.js
> +    Extension: sipc.ink.CloudMusic,
这个应该是

`Extension: MusicExtension`

这个 key 的意思是，这个扩展的 class name 是什么。

2023-09-04 03:17 UTC, sylarhcn commented on sipc.ink/CloudMusic/CloudMusic.js
> +          搜索音乐: '搜索音乐 [name]',
翻译的 key 需要使用英文，比如 “搜索音乐” 应该是 "search" 或者 “searchMusic”
另外，最好是在 key 链接上扩展 id 作为前缀，避免被其他翻译 key 覆盖。这个 scratch 的翻译数据都是放在一起的。

比如"sipc.ink.CloudMusic.search" 或者 "cm.search"，反正就是让他特别一点，不容易被覆盖。

2023-09-04 03:42 UTC, sylarhcn commented on sipc.ink/CloudMusic/CloudMusic.js
> +    l10m: {
写错了，应该是 l10n

2023-09-04 10:31 UTC, SIPC commented
啊？

2023-09-05 05:52 UTC, sylarhcn commented on sipc.ink/CloudMusic/CloudMusic.js
> +    pausemusic() {
可以学一下驼峰命名比如，比如这个函数命名用驼峰的话就是，pauseMusic

2023-09-05 10:18 UTC, SIPC commented on sipc.ink/CloudMusic/CloudMusic.js
> +    pausemusic() {
好的

2023-09-27 08:39 UTC, sylarhcn approved these changes

2023-09-27 08:39 UTC, merged