More mouse
Gandi-IDE/custom-extension pull request #114
Opened 2023-09-03 15:55 UTC by little-starts

fix(block):修复了之前未隐藏的已下线积木
feat(block):新增切换鼠标样式为角色造型
feat(block):新增碰到手指积木

2023-09-04 03:22 UTC, sylarhcn requested changes

2023-09-04 03:22 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +	gyroscope(args) {
这种特型设备用的功能，不要杂糅到一个扩展里面

新开的一个扩展吧。

2023-09-04 03:22 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +	istouch(args, util) {
虽然不影响了什么，但是全小写、全大写的函数命名风格是很不好的。
函数/变量命名方式，请使用驼峰命名规则

2023-09-04 06:38 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +	gyroscope(args) {
该积木已隐藏

2023-09-04 07:00 UTC, little-starts commented on wit_cat/More_Mouse.js
> +	istouch(args, util) {
已经修复了

2023-09-27 08:41 UTC, sylarhcn approved these changes

2023-09-27 08:42 UTC, merged