Lily's comment extension
Gandi-IDE/custom-extension pull request #116
Opened 2023-09-06 13:45 UTC by fath11

Alright, alright, in my first pull request, I don't know if my code works; in the second one, I realized the extension needs to be in CCW-Approved format to get published. I wasted so much of your time, but now I am 100% sure I don't miss anything, OK?

LilyMakesThings made the extension from Turbowarp, and they allow me to use their code, AND the code is in CCW-Approved format.

Original code: https://github.com/TurboWarp/extensions/blob/5c28a7da640acd4ae0c0de8f75e4f478dbf9a9c9/extensions/Lily/CommentBlocks.js#L9

If I need to correct something, please let me know. Thank you very much.

-Fath11 to the respected Gandi devs.

2023-09-07 02:48 UTC, fath11 commented
Lily's comment: https://github.com/fath11/custom-extension/blob/main/Fath/Lily's%20comment.js

2023-09-07 02:49 UTC, fath11 commented
Fath's Web: https://github.com/fath11/custom-extension/blob/main/Fath/web.js (converted to CCW-Approved format)

2023-09-08 01:27 UTC, fath11 commented
@sylarhcn ?

2023-09-26 05:31 UTC, sylarhcn requested changes

2023-09-26 05:31 UTC, sylarhcn commented on Fath/0832 rxFS.js
> +                defaultValue: "https://0832k12.github.io/rxFS/hello.txt",
same reason as “Web Extension” about web asset accessing risk

2023-09-26 05:31 UTC, sylarhcn commented on Fath/BigInt.js
approved
Cloud you add some author info in it like name, personal homepage link or email address.
you can add a function in class to return author's info like below
`getAuthor () {
  return {name:'xxx', link:'xxx'}
}`
if have more then one author, you can return a array

2023-09-26 05:31 UTC, sylarhcn commented on Fath/Morecomparison.js
approved
Cloud you add some author info in it like name, personal homepage link or email address.
you can add a function in class to return author's info like below
getAuthor () { return {name:'xxx', link:'xxx'} }
if have more then one author, you can return a array

2023-09-26 05:31 UTC, sylarhcn commented on Fath/dataanalysis.js
approved
Cloud you add some author info in it like name, personal homepage link or email address.
you can add a function in class to return author's info like below
getAuthor () { return {name:'xxx', link:'xxx'} }
if have more then one author, you can return a array

2023-09-26 05:31 UTC, sylarhcn commented on Fath/firstMadeInGExtension.js
this test file shoudn't submit in PR.just keep in your local or dev branch

2023-09-26 05:31 UTC, sylarhcn commented on example/normal-ext.js
this example file is a demo for everyone to show how to make a extension, you shouldn't modify it, just dont commit this file change or revert it to Initial state

2023-09-26 05:31 UTC, sylarhcn commented on replit.nix
this is your ide config? it should be added in .gitigore, shouldn’t commit in PR

2023-09-26 05:31 UTC, sylarhcn commented on package.json
I dont't any of your js is using those package in dependencies? so this package.json is unnecessary

2023-09-26 05:40 UTC, sylarhcn commented
> @sylarhcn ?

oi~，Hi there!  I’ve been quite busy with other tasks and bug fixes lately, I reviewed all of your pull requests.  must say, it’s impressive that you’ve submitted these extensions.  Please take a moment to read my comment, there are issues in some extensions.

2023-09-26 07:19 UTC, kukemc commented
https://extensions.turbowarp.org/Xeltalliv/clippingblending.js
Can you port this extension over as well?,  If so, thank you very much!

2023-09-26 12:11 UTC, fath11 commented on example/ccw-approved-ext.js
i didnt?

2023-09-26 12:14 UTC, fath11 commented on Fath/firstMadeInGExtension.js
right, i commit it to this repo to test something but forgot to redo the commit

2023-09-26 13:08 UTC, fath11 commented on package.json
ok

2023-09-26 13:09 UTC, fath11 commented
> oi~，Hi there! I’ve been quite busy with other tasks and bug fixes lately, I reviewed all of your pull requests. must say, it’s impressive that you’ve submitted these extensions. Please take a moment to read my comment, there are issues in some extensions.

seeing ~ is a relief to me since i thought i might be disturbing you(i am not right?)

2023-09-26 13:40 UTC, fath11 commented on Fath/dataanalysis.js
i can convert these extensions to CCW-Approved format, should be done by the end of the week since i have school

2023-09-26 13:45 UTC, fath11 commented on example/normal-ext.js
i put the example folder to .gitignore, is this good?

2023-10-13 13:16 UTC, qxsck commented
I should release data analysis,you can delete it

2023-10-14 00:42 UTC, fath11 commented
> I should release data analysis,you can delete it

ok

2023-10-15 13:07 UTC, FurryR commented
Did you add the **Simplified Chinese** (zh_cn) translation?

2023-10-16 03:19 UTC, fath11 commented
i doesnt put any translation on morecomparison.js because the blocks inside of it doesn't need any.

i hope you don't mind

2023-10-16 13:32 UTC, fath11 commented
Encoding converted to ccw format 😎

2023-10-16 13:36 UTC, fath11 commented
and finally example folder is reverted(i am very sorry for touching it in the first place)

2023-10-16 13:38 UTC, fath11 commented
> Did you add the **Simplified Chinese** (zh_cn) translation?

yes

2023-10-31 02:19 UTC, NexusKitten commented
How come you're calling it _Lily's_ comment extension? It's comment blocks, I don't think you have to give credit for something so simple

2023-10-31 02:41 UTC, fath11 commented
> How come you're calling it _Lily's_ comment extension? It's comment blocks, I don't think you have to give credit for something so simple

lily is fine with it 🤷

2023-11-15 14:11 UTC, FurryR commented
> How come you're calling it _Lily's_ comment extension? It's comment blocks, I don't think you have to give credit for something so simple

You can't reproach that because you ARE NOT one of the extension developers.

2023-11-15 18:11 UTC, NexusKitten commented
I've been banned from the repo for childish reasons but I have contributed
lmao

On Wed, Nov 15, 2023, 9:11 AM 凌 ***@***.***> wrote:

> How come you're calling it *Lily's* comment extension? It's comment
> blocks, I don't think you have to give credit for something so simple
>
> You can't reproach that because you ARE NOT one of the extension
> developers.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Gandi-IDE/custom-extension/pull/116#issuecomment-1812606002>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6KDE3YLBE5PS3ZJWHFUFVDYETES3AVCNFSM6AAAAAA4NL2BSOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJSGYYDMMBQGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-11-20 00:49 UTC, fath11 commented
I renamed Lily's Comment to Comment blocks. I feel like it's the right thing to do. I am sorry if I offended anyone.

2023-12-05 07:02 UTC, sylarhcn requested changes
this PR contains 4 extenison JS files？
from your message，only comment blocks is what your want to merge.
It would be better to split this PR into each extension file for easier version control

2023-12-05 07:03 UTC, sylarhcn commented
btw, your scratchHub was merged, congrats

2023-12-06 03:41 UTC, fath11 commented on .config/configstore/update-notifier-npm.json
I will fix this and split this PR; thank you soo much for merging scratch hub. It made my day

2023-12-07 02:52 UTC, fath11 commented
@SIPC i will delete Encoding from my repo; since you are the original creator, you should add it to yours instead

2023-12-07 03:01 UTC, closed without merging

2023-12-07 03:01 UTC, fath11 commented
#140 #141 #142