在arkos拓展增加数据分析积木
Gandi-IDE/custom-extension pull request #117
Opened 2023-09-17 11:29 UTC by qxsck

2023-09-26 06:36 UTC, sylarhcn requested changes

2023-09-26 06:36 UTC, sylarhcn commented on Arkos/projectWith30.js
建议单独建一个新的扩展来容纳这些功能。
非必要的情况下不要打破“一个扩展只解决一个问题”的原则。
大杂烩在用户端不友好，不仅不好索引和学习，还会消耗很多额外的性能。

2023-09-26 06:36 UTC, sylarhcn commented on qxsck/str_mani.js
> -        extensionId: 'strmani1',
这个在更新扩展的 ID 吗，已上线扩展不能修改 ID，会导致所有已经使用的作品不能正确的加载扩展

2023-09-28 11:00 UTC, qxsck commented on Arkos/projectWith30.js
好的

2023-09-28 11:00 UTC, qxsck commented on qxsck/str_mani.js
> -        extensionId: 'strmani1',
“1”是为了测试时加的，pr时忘记改了，非常抱歉

2023-09-28 11:09 UTC, closed without merging