🔼添加项目扩展
Gandi-IDE/custom-extension pull request #120
Opened 2023-09-27 13:17 UTC by 0832k12

这个扩展可以查看项目目前的状态。

2023-10-03 03:14 UTC, fath11 commented
yeah...
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/fdea9c65-a74d-4f2d-bf45-8acec44560f5)

2023-10-03 03:23 UTC, fath11 commented
i tried the extension and it doesnt work?

2023-10-06 07:41 UTC, 0832k12 commented
> i tried the extension and it doesnt work?
> 
> i would also suggest you make variables, func, etc names in English because this is an international repo.

Thanks! I'll change it immediately.

2023-10-06 07:45 UTC, 0832k12 commented
> i tried the extension and it doesnt work?
> 
> i would also suggest you make variables, func, etc names in English because this is an international repo.

It works in TurboWarp unsandbox environment because of the use of dynamic menus. It does not work in a sandbox environment.
![image](https://github.com/Gandi-IDE/custom-extension/assets/70421730/a5af8a4d-4092-4a8c-afb4-4a4d72037529)

2023-10-07 02:08 UTC, fath11 commented
i think you would need to use CCW-Approved format instead, i am not sure if it will run unsandboxed or not but i the current format you are using will not run the extension unsandboxed

2023-10-07 09:04 UTC, sylarhcn commented
> i think you would need to use CCW-Approved format instead, i am not sure if it will run unsandboxed or not but the current format you are using will not run the extension unsandboxed

you can use "load custom extension" button to load .
it's unsandboxed.

CCW-Approved format is outdated, documentation hasn't caught up yet, I will update it later.

2023-10-07 09:08 UTC, sylarhcn requested changes
Don't use Chinese to represent functions or variables in your code

2023-10-07 10:02 UTC, 0832k12 commented
> 不要在代码中使用中文来表示函数或变量 // 不要用中文来表示函数名和变量名，中文只应该在 string 中使用。

了解

2023-10-10 06:40 UTC, sylarhcn requested changes

2023-10-10 06:40 UTC, sylarhcn commented on 0832/Project/Project.js
> +    const vm = Scratch.vm;
你在 gandi 测试过你的扩展了吗。
gandi 并没有对扩展开放 vm 的访问权限。
gandi 中的扩展可以访问 runtime。

2023-10-15 13:20 UTC, FurryR commented on 0832/Project/Project.js
> +    const vm = Scratch.vm;
题外话：现在可以通过 runtime，利用一些小技巧获得 vm 了。无论是 ClipCC、Turbowarp、小码王、A营还是原版 Scratch 都支持。

2023-11-02 03:41 UTC, 0832k12 commented on 0832/Project/Project.js
> +    const vm = Scratch.vm;
> 题外话：现在可以通过 runtime，利用一些小技巧获得 vm 了。无论是 ClipCC、Turbowarp、小码王、A营还是原版 Scratch 都支持。

怎么做？

2023-12-04 06:38 UTC, sylarhcn requested changes

2023-12-04 06:38 UTC, sylarhcn commented on 0832/Project/Project.js
> +    const vm = Scratch.vm;
你代码中的很多功能不需要访问vm，访问 runtime 就可以了。
gandi 扩展是可以访问 runtime 。在扩展 class 的 constructor 中就会传入 runtime 。
即使你使用的 vm.toJson() 也是和你低效的手段，因为 runtime 中已经提供了所有 target 了。不需要 toJson 再重新解析了，你这样其实是很低效的。

2024-03-12 09:06 UTC, sylarhcn reviewed
缺少 info 注册信息哦
你可以参考其他扩展作者的写法
类似这个，用处是 Gandi 用来将你的扩展展示在扩展商店的
`{
info: {
      name: `moreSensing.extensionName`,
      description: `moreSensing.description`,
      extensionId: 'moreSensing',
      iconURL: moreSensingCover,
      insetIconURL: moreSensing_icon,
      featured: true,
      disabled: false,
      docsURI: 'https://learn.ccw.site/article/a6ad9600-20e8-46f2-9bfd-721e0f3e1e6c',
    },
    l10n: {
      'zh-cn': {
        'moreSensing.extensionName': '更多侦测',
        'moreSensing.description': '提供云时间、更方便的按键检测等功能',
      },
      en: {
        'moreSensing.extensionName': 'More Sensing',
        'moreSensing.description': 'Provide cloud time, better key detection and other functions.',
      }
    },
}`

2024-03-12 10:04 UTC, 0832k12 commented
> 缺少 info 注册信息哦 你可以参考其他扩展作者的写法 类似这个，用处是 Gandi 用来将你的扩展展示在扩展商店的 `{ info: { name: `moreSensing.extensionName`, description: `moreSensing.description`, extensionId: 'moreSensing', iconURL: moreSensingCover, insetIconURL: moreSensing_icon, featured: true, disabled: false, docsURI: 'https://learn.ccw.site/article/a6ad9600-20e8-46f2-9bfd-721e0f3e1e6c', }, l10n: { 'zh-cn': { 'moreSensing.extensionName': '更多侦测', 'moreSensing.description': '提供云时间、更方便的按键检测等功能', }, en: { 'moreSensing.extensionName': 'More Sensing', 'moreSensing.description': 'Provide cloud time, better key detection and other functions.', } }, }`

好的

2024-03-28 13:28 UTC, FurryR commented on 0832/Project/Project.js
> +Scratch.translate.setup({
要使用 Scratch 对象需要进行 IIFE。

```js
(function (Scratch) {
   // 代码
})(Scratch);
```

在未来，Gandi IDE 全局 Scratch 对象的生命周期将会变更，不再长久存在。

2024-03-28 13:31 UTC, FurryR commented on 0832/Project/Project.js
> +                    text: Scratch.translate({ id: 'TotalUsedBlocks', default: 'Total Used Blocks' })
请在 id 前添加 namespace（命名空间），否则会导致污染全局翻译。

2024-03-28 13:32 UTC, FurryR commented on 0832/Project/Project.js
> +Scratch.extensions.register(new Project());
tempExt 和 Scratch.extensions.register 不需也不可以同时出现。

2024-03-28 13:33 UTC, FurryR commented on 0832/Project/Project.js
> +                    opcode: 'NumberOfBlockTypes',
耗时操作请使用 `disableMonitor: true` 来禁止 monitor。

2024-03-28 13:34 UTC, FurryR requested changes
需要修改。

2024-03-29 11:39 UTC, sylarhcn requested changes

2024-03-29 11:39 UTC, sylarhcn commented on 0832/Project/Project.js
> +    const extensionId = 'Project';
建议，这个id 最好加入你的个人前缀，如果是自己的原创扩展的话。为了避免过于简单容易重复的问题。
比如 arkos 的扩展就叫 'arkos_extxxxx' 这种

2024-03-31 06:37 UTC, fath11 commented
what is "segment"?

2024-04-16 12:37 UTC, 0832k12 commented
现在还需要我做什么？

2024-05-13 08:39 UTC, sylarhcn requested changes

2024-05-13 08:39 UTC, sylarhcn commented on 0832/Project/Project.js
> +    const extensionId = '0832_Project';
sorry，之前给你的例子是有问题的，虽然可以使用 '_' 在扩展 id 中，但是在 scratch 中，积木的 opcode (你可以认为这个 opcode 是一个积木唯一定义 id) 拼接也用到 '_' , 所以在扩展 id 中使用 '_'，可能更容易导致一些不严谨的代码错误。

比如根据积木的 'opcode: 0832_Project_TotalUsedBlocks' 来辨别，这个积木是属于哪个扩展的。
如果我们有 0832_Project 与 0832 两个扩展 id，并且 0832 中还存在一个积木 opcode 定义为 ’Project_TotalUsedBlocks‘ 的积木。

那此时，就无法分班当前这个积木是哪个扩展的了。

所以，新建的扩展，id 请不要包含 '_' , 你可以用 ’-‘ 或者别的符号代替。

2024-05-27 08:54 UTC, merged