File_Helper V2.8
Gandi-IDE/custom-extension pull request #156
Opened 2023-12-28 07:49 UTC by little-starts

feat(block):zip相关积木
feat(block):按照读取方式打开上次打开的文件

2024-01-05 11:20 UTC, sylarhcn requested changes

2024-01-05 11:20 UTC, sylarhcn commented on wit_cat/File_Helper.js
> +scriptElement.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.7.1/jszip.min.js';
建议直接保存到你的目录，直接 import 吧。不要用这种方式。容易和外部代码冲突

2024-01-14 03:47 UTC, little-starts commented on wit_cat/File_Helper.js
> +scriptElement.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.7.1/jszip.min.js';
试过了，但是他没有export，无法import，我又改不来，就只能这样了

2024-03-12 09:14 UTC, sylarhcn requested changes

2024-03-12 09:14 UTC, sylarhcn commented on wit_cat/File_Helper.js
> +!function (t) { if ("object" == typeof exports && "undefined" != typeof module) module.exports = t(); else if ("function" == typeof define && define.amd) define([], t); else { ("undefined" != typeof
既然 base64 你都 import 了，为啥不把这个 jszip 的压缩代码也做成 import 的方式呢。

2024-03-12 12:29 UTC, little-starts commented on wit_cat/File_Helper.js
> +!function (t) { if ("object" == typeof exports && "undefined" != typeof module) module.exports = t(); else if ("function" == typeof define && define.amd) define([], t); else { ("undefined" != typeof
我不会，试过了，最后没办法才这么做的

2024-03-15 08:17 UTC, closed without merging