Bilioicik的 简单返回值拓展
Gandi-IDE/custom-extension pull request #196
Opened 2024-03-12 13:28 UTC by MoreBugOfDog

按照要求新开了PR，请审核

2024-03-22 06:17 UTC, sylarhcn requested changes
我认为该扩展可能有问题的地方
1. 扩展中大量使用 JSON.parse,stringfy 来实现功能。这可能是低效的，这些积木都必须的吗
2. 扩展中有较多和其他专用扩展重复的功能，我们不再提倡提交大杂烩的扩展，希望扩展是基于解决某种需求或问题而设计的，精简的积木。
3. 扩展的名字，描述和扩展中的积木没有具体联系


请具体描述一下
1. 概括要解决的问题
2. 举例描述一下该扩展的使用场景，在创作中

你可以到讨论群获取更多讨论和建议。

2024-03-23 12:33 UTC, MoreBugOfDog commented
bilioicik修复了上述问题，请求审核。

2024-03-24 10:50 UTC, bilioicik commented
> 我认为该扩展可能有问题的地方
> 
> 1. 扩展中大量使用 JSON.parse，stringfy 来实现功能。这可能是低效的，这些积木都必须的吗
> 2. 扩展中有较多和其他专用扩展重复的功能，我们不再提倡提交大杂烩的扩展，希望扩展是基于解决某种需求或问题而设计的，精简的积木。
> 3. 扩展的名字，描述和扩展中的积木没有具体联系
> 
> 请具体描述一下
> 
> 1. 概括要解决的问题
> 2. 举例描述一下该扩展的使用场景，在创作中
> 
> 你可以到讨论群获取更多讨论和建议。

2024-03-24 10:56 UTC, bilioicik commented
I am coming. I used to use Google. That's why l can't sign up Gayhub. ( Now I use Microsoft Edge.

2024-03-24 10:57 UTC, bilioicik commented
You need to see this: https://www.ccw.site/post/306d54d0-b83a-43f3-ba84-bd41a7183239

2024-03-24 10:58 UTC, bilioicik commented
I am not very familiar with Github now.

2024-03-28 13:36 UTC, FurryR commented on .gitignore
>  .cache
冗余文件，请删除

2024-03-28 13:38 UTC, FurryR commented on bilioicik/simple_Operators.js
> +const { Scratch } = window;
请勿假定 `Scratch` 对象存在于 `window`。它可能存在于 `globalThis`（Turbowarp）或当前作用域（Eureka）上，但不一定存在于 `window` 上。

2024-03-28 13:39 UTC, FurryR commented on bilioicik/simple_Operators.js
> +                'simpleOperatorsdocs':'文档',
请为所有的翻译添加 namespace 也即命名空间，否则会导致全局翻译污染。

2024-03-28 13:39 UTC, FurryR commented on bilioicik/simple_Operators.js
> +                '---'+this.formatMessage('simpleOperatorstip'),
此写法不标准。

2024-03-28 13:47 UTC, FurryR commented on bilioicik/simple_Operators.js
> +    rArrayremovenotsmallnumber(args){
函数命名需要遵循小驼峰。

2024-03-28 13:48 UTC, FurryR commented on bilioicik/simple_Operators.js
> +        return JSON.parse(args.a).findIndex(i => i > args.b)
您是完全不做入参检查的么？

2024-03-29 03:13 UTC, bilioicik commented on .gitignore
>  .cache
emmm…很抱歉，我并不晓得这些。我已经给不止一个人看过了，但是从来没有人指出过这些问题。我也以为能正常运行不出bug就可以了。感谢您的指出。我会花时间研究的。

2024-03-29 03:14 UTC, bilioicik commented on bilioicik/simple_Operators.js
> +const { Scratch } = window;
okk.

2024-03-29 03:14 UTC, bilioicik commented on bilioicik/simple_Operators.js
> +                'simpleOperatorsdocs':'文档',
我还是不太清楚你所用的专属名词“namespace”的具体含义。命名空间又是什么。

2024-03-29 03:14 UTC, bilioicik commented on bilioicik/simple_Operators.js
> +                '---'+this.formatMessage('simpleOperatorstip'),
具体指onClick吗，白猫的fps就是这么写的啊

2024-03-29 03:14 UTC, bilioicik commented on bilioicik/simple_Operators.js
> +    rArrayremovenotsmallnumber(args){
我不清楚你所用的专属名词“小驼峰”的具体含义。

2024-03-29 03:14 UTC, bilioicik commented on bilioicik/simple_Operators.js
> +        return JSON.parse(args.a).findIndex(i => i > args.b)
这样便于运行速度，并且字符串的数字也能使用大于小于号而不出错。

2024-03-29 14:49 UTC, bilioicik commented on bilioicik/simple_Operators.js
> +    rArrayremovenotsmallnumber(args){
okk.

2024-03-29 14:50 UTC, bilioicik commented on bilioicik/simple_Operators.js
> +                'simpleOperatorsdocs':'文档',
好像懂了，namespace是那扩展名加一点吗

2024-03-29 14:52 UTC, bilioicik commented on bilioicik/simple_Operators.js
> +const { Scratch } = window;
所以多莉pro的写法也是错误的吗
![image](https://github.com/Gandi-IDE/custom-extension/assets/164740037/688818b0-a09a-4cdf-afae-9358b80d2e3b)

2024-03-29 14:54 UTC, bilioicik commented on bilioicik/simple_Operators.js
> +        return JSON.parse(args.a).findIndex(i => i > args.b)
关于这一点很必要吗？我只是想这样便于运行速度，毕竟字符串的数字也能使用大于小于号而不出错。

2024-03-29 14:57 UTC, bilioicik commented on bilioicik/simple_Operators.js
> +                '---'+this.formatMessage('simpleOperatorstip'),
白猫的fps
![image](https://github.com/Gandi-IDE/custom-extension/assets/164740037/4374c8fc-a8a1-4b58-9ed2-d761e42447e6)

2024-03-29 22:51 UTC, fath11 commented on bilioicik/simple_Operators.js
> +                '---'+this.formatMessage('simpleOperatorstip'),
he is referring to  `'---' + this.formatMessage('simpleOperatorstip')`, gandi now supports the use of `Scratch.BlockType.LABEL` like this
```js
{
  blockType: Scratch.BlockType.LABEL,
  text: "Square Pen Blocks",
},
```

2024-03-30 02:05 UTC, bilioicik commented on bilioicik/simple_Operators.js
> +                '---'+this.formatMessage('simpleOperatorstip'),
Thanks, I see.

2024-03-30 09:36 UTC, MoreBugOfDog commented on .gitignore
>  .cache
> 嗯......很抱歉，我并不晓得这些。我已经给不止一个人看过了，但是从来没有人指出过这些问题。我也以为能正常运行不出bug就可以了。感谢您的指出。我会花时间研究的。

这个我帮你处理下。

2024-03-30 09:40 UTC, MoreBugOfDog commented on bilioicik/simple_Operators.js
> +const { Scratch } = window;
我想，bilioicik不打算将其适配到tw，因此只要gandi-IDE可以加载此拓展即可了，感谢你的review

2024-03-30 09:41 UTC, MoreBugOfDog commented on bilioicik/simple_Operators.js
> +                'simpleOperatorsdocs':'文档',
> 好像懂了，namespace是那扩展名加一点吗

是的，这需要手动更改，比较费时间的。

2024-04-03 14:00 UTC, closed without merging