提交 更多运算（numpro.js） 拓展
Gandi-IDE/custom-extension pull request #197
Opened 2024-03-12 13:30 UTC by MoreBugOfDog

按照要求新开了PR，请审核

2024-03-14 16:12 UTC, Arkos123 commented
那个设置哪些积木显示的窗口怎么没了，我很喜欢那个功能（）

2024-03-14 16:16 UTC, Arkos123 commented
![VUW}ZEAWZ7YH7PBZOU~TWFL](https://github.com/Gandi-IDE/custom-extension/assets/101853866/0f2f2464-79e4-4f3a-9e8e-d1af631b15ff)
这些积木感觉都可以删除吧（因为已经有字符串扩展了）

2024-03-15 00:42 UTC, fath11 commented
Here are my suggestions
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/6436bec2-fc2d-4630-aaa9-441d7e5afda1)
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/90290d97-de30-4ea9-b15e-d7dec1ef1380)
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/9ec82148-65c1-408d-9389-ed76a6ad2c52)
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/a0a7d8d7-c94b-4218-a430-24e388a3e69d)

everything else can stay

2024-03-15 07:40 UTC, sylarhcn requested changes
Agree with the above two suggestions on streamlining the blocks

2024-03-22 06:37 UTC, sylarhcn requested changes
看起来，扩展提供了 3 个不同类型数据的处理的语法糖和一些集成 api
1. 那是不是可以按照不同类型分成不同扩展了，我们现在不提倡搞大集合。
2. 部分语法糖，感觉过于内聚，晦涩了。比如“取余”操作，你做成了’在 a 到 b 中循环‘，不经非常难理解， 也和我们正常环境中接触到数学知识没有匹配上。我觉得可能不是很好的设计。应该中通用易懂点。、
3. 字符串那个块的积木，我没用没用，用成功，为什么会有单独的变量积木就是返回输入的字符串？链接积木没有使用成功。

建议在扩展讨论群中，获取其他扩展作者的建议。

2024-04-05 02:15 UTC, MoreBugOfDog commented
zh-cn:
与 bilioicik 开发完成未PR的拓展合并，已经经过 bilioicik 的同意。
修复了review出的问题。

en:
Merged with bilioicik to finish development of un-PR'd extensions, with bilioicik's permission.
Fixed problems with review.
@fath11 @sylarhcn @FurryR

2024-04-05 06:26 UTC, bilioicik commented
关于以小驼峰来命名函数这点实在改不动，已经在ccw上跟HGN商量过了，HGN表示能接受。下次命名一定符合规范。

2024-04-05 07:44 UTC, MoreBugOfDog commented
> 关于以小驼峰来命名函数这点实在改不动，已经在ccw上跟HGN商量过了，HGN表示能接受。下次命名一定符合规范。

× HGN √HCN

2024-04-05 09:39 UTC, bilioicik commented
关于以小驼峰来命名函数这点实在改不动，已经在ccw上跟HCN商量过了，HCN表示能接受。下次命名一定符合规范。

2024-04-05 23:37 UTC, fath11 commented
My problems with this extension still stand. All of these functionalities can already be done with existing extensions. You should focus more on #195

2024-04-06 02:38 UTC, MoreBugOfDog commented
> 我对这个扩展的问题仍然存在。所有这些功能都已经可以通过现有的扩展来完成。你应该更多地关注#195

Hello fath11!
We will be further culling or hiding duplicate blocks for this extension.
Thank you for your review.
For PR https://github.com/Gandi-IDE/custom-extension/pull/195 , we are making changes to him, thank you for your attention.

2024-04-06 03:52 UTC, FurryR commented on MoreBugOfDog/numpro/Operation_pro.js
> +  } = Scratch;
为了兼容性考虑，需要使用 IIFE 格式才能使用 Scratch 对象，这涉及到扩展的加载原理。

```js
(function (Scratch) {
  // 你的代码。
})(Scratch);
```

2024-04-06 03:54 UTC, FurryR commented on MoreBugOfDog/numpro/Operation_pro.js
> +        if (symbol === 'parallel') return ((arg1 - arg2) % 180) === 0
这段重复代码过多了。

2024-04-06 03:56 UTC, FurryR commented on MoreBugOfDog/numpro/Operation_pro.js
> +        return JSON.parse(args.a).some(i => i >
导向不良

2024-04-06 07:39 UTC, fath11 commented on MoreBugOfDog/numpro/Operation_pro.js
> +        if (symbol === 'parallel') return ((arg1 - arg2) % 180) === 0
Switch statements being forgotten 🥲

2024-04-06 09:33 UTC, bilioicik commented on MoreBugOfDog/numpro/Operation_pro.js
> +        return JSON.parse(args.a).some(i => i >
![image](https://github.com/Gandi-IDE/custom-extension/assets/164740037/245545f8-552b-4fb7-8678-f66e19c047a0)
“导向不良”是指连续堆叠功能类似的积木吗？我正在做它们的精简版本

2024-04-06 09:46 UTC, bilioicik commented
最新更改：numpro的那些重复的if更改为了简洁的switch和case；numpro的那些与已有扩展雷同的关于大于小于判断功能被删除；字符互换积木中的参数默认值分别更改为了ccw、c、w；新出了四个精简化积木；使用 IIFE 格式。

2024-04-06 09:47 UTC, bilioicik commented
最新更改：numpro的那些重复的if更改为了简洁的switch和case；numpro的那些与已有扩展雷同的关于大于小于判断功能被删除；字符互换积木中的参数默认值分别更改为了ccw、c、w；新出了四个精简化积木；使用 IIFE 格式。

2024-04-06 09:48 UTC, bilioicik commented
最新更改：
numpro重复的if更改为了简洁的switch和case；
numpro与已有扩展雷同的关于大于小于判断功能被删除；
字符互换积木中的参数默认值分别更改为了ccw、c、w；
新出了四个关于数组中元素大小的精简化积木；
改为使用 IIFE 格式。

2024-04-06 10:22 UTC, MoreBugOfDog commented
All issues reviewed have been resolved, please review again.
已经解决所有审核出的问题，请再次审查。
@sylarhcn @fath11 @FurryR

2024-04-06 14:38 UTC, bilioicik commented
额，我还是更喜欢原来的descp。首先这个扩展还涉及字符串数组对象，跟这个描述的“数学”本身关系并不多；其次这个描述既长又太夸张了。我选择的“Green for Go”出自Thomas Greenberg的专辑《Something Simple》的第17首；PR[#195](https://github.com/Gandi-IDE/custom-extension/pull/195)的“Moving Onwards”也是出自《Something Simple Acoustic》；封面更是印证这点，算是一个彩蛋了。

2024-04-06 14:47 UTC, bilioicik commented
> 我对这个扩展的问题仍然存在。所有这些功能都已经可以通过现有的扩展来完成。你应该更多地关注#195

我刚改正没按小驼峰命名的错误，计划编写使角色按照函数图像轨迹运动的积木，积木类型conditional，这样它运动过程中可以运行别的积木。

2024-05-11 11:32 UTC, sylarhcn requested changes
你有超过 200 个积木。我认为这个扩展的使用负担会非常高。

请保持扩展的简洁

或提供设计目标与方案给大家讨论

(超过200个积木的结论，通过 l10n 数量大概判断的，因为单个语言的 l10n 有 300 条)

2024-05-11 11:32 UTC, sylarhcn commented on .gitignore
请不要无故删除 ignore 文件中内容

2024-06-13 13:14 UTC, closed without merging