File Helper V2.8
Gandi-IDE/custom-extension pull request #199
Opened 2024-03-15 09:42 UTC by little-starts

pref(code):使用npm添加jszip组件
feat(block):zip相关积木
feat(block):按照读取方式打开上次打开的文件

2024-03-15 16:04 UTC, kukemc commented
Has passed the audit.

2024-03-22 07:07 UTC, sylarhcn requested changes
如果你是 webpack 或者别的 js 代码打包工具的话，有几个需要注意的。

1. tempExt 是仅用于测试的入口，tempExt 的定义，不要写入到你的扩展 class 文件中。
你可以将 tempExt 单独写到一个文件，作为你扩展的注册入口文件。
2. 静态资源文件，比如 扩展icon 和 封面，也请提供独立的文件或者模块。（带包后内联到压缩代码中，我无法单独复制出来，上传 CDN）
3. 提供单独的 info 文件，里面扩展的基本信息（就是 tempExt 中填写的内容，可以和 tempExt为同一个文件）

2024-03-29 11:22 UTC, sylarhcn reviewed
既然你都告诉 webpack 了，那 jszip 要不要试试用 npm 来安装。
然后学习下 @kukemc ,把 package.json 搞标准点。

这样你就学会前端的基础项目工作流了，你写其他前端代码也可以用了。

2024-04-09 14:47 UTC, FurryR requested changes
修改意见如上。

2024-05-11 10:48 UTC, sylarhcn reviewed
看起来这个扩展里面包含了
zip 文件处理
文本文件处理

我建议将他们分开，这样可以显著降低单个扩展的复杂度

2024-05-11 10:48 UTC, sylarhcn commented on wit_cat/File_Helper/extension.js
> +                "WitCatFileHelper.name": "白猫的文件助手",
扩展中有众多建键值的操作，建议文件助手保证简单，只包含文件处理相关的功能。
键值操作获取可以单独做一个扩展方案吧。

2024-05-14 02:02 UTC, little-starts commented on wit_cat/File_Helper/extension.js
> +                "WitCatFileHelper.name": "白猫的文件助手",
这个是之前曾上线过，后来下架的功能，所以无法删除，当然如果你要求完全删除也可以

2024-05-14 02:02 UTC, little-starts commented
> 看起来这个扩展里面包含了
> zip 文件处理
> 文本文件处理
> 
> 我建议将他们分开，这样可以显著降低单个扩展的复杂度
> 如果他们有公用的工具方法，你也可以把他抽象出来成为单独的 util ，这样代码组织度也会更好

分开应该怎么处理，是让两个扩展都有打开文件下载文件等一样的积木还是需要先加载文件助手才能加载zip扩展作为其前置？

2024-05-15 05:51 UTC, closed without merging