创建 Tilemap 扩展
Gandi-IDE/custom-extension pull request #203
Opened 2024-03-17 07:15 UTC by Nightre

这个应该是beta版，我只人工测试了一遍，未来性能可能会更好，能不能放到开发中的扩展？

## 文件

* timeap.js 扩展文件
* demo.sb3 demo 作品
* icon.png 图标
* cover.png 封面
* info.json

我修改了 scratch-render的webglrender的drawthese方法（在src/override.js中）
。可能需要修改，在src/override.js所有我修改的都标注了by:nights，否则骨骼，图层管理，雷神，可能无法与tilemap一起使用

这个是打包好了的，没打包的：[https://github.com/Nightre/tilemap](https://github.com/Nightre/tilemap)

## 功能

* 高性能瓦片地图
* 等距地图 （菱形）+ 正交地图（正方形）
* 瓦片集的旋转缩放颜色偏移
* 支持多纹理
* 多层地图
* 角色图层
* 角色在地图中Y图层
* 瓦片动画
* 坐标换算

## 性能：

集成显卡（Intel(R) UHD Graphics 620 ）渲染1.5万个80*80像素的纹理稳定 60FPS

2024-03-17 11:24 UTC, FurryR commented on Nights/tilemap/tilemap.js
> +    const gl = this._gl;
这里的 _drawThese 和 Gandi 的 Spine 骨骼并不兼容。请考虑一下改为注入。

2024-03-17 11:25 UTC, FurryR commented on Nights/tilemap/tilemap.js
> +          throw new Error("你这样我很难帮你办事呀");
这里请认真一点，如果有用户，尤其是外国用户遇到这个 bug 将不知所措。

2024-03-17 11:26 UTC, FurryR commented on Nights/tilemap/tilemap.js
> +  const SCRATCH_TYEP = {
typo

2024-03-17 11:27 UTC, FurryR requested changes
非常好扩展，但是需要修改。

2024-03-17 11:35 UTC, Nightre commented on Nights/tilemap/tilemap.js
> +          throw new Error("你这样我很难帮你办事呀");
改了

2024-03-17 11:36 UTC, Nightre commented on Nights/tilemap/tilemap.js
> +  const SCRATCH_TYEP = {
也改了

2024-03-18 06:00 UTC, Arkos123 commented
https://github.com/Gandi-IDE/custom-extension/assets/101853866/7238c656-6b5f-45b2-9c2a-229a4fe31d8e





等距地图显示有点bug

2024-03-22 07:19 UTC, sylarhcn commented on Nights/tilemap/info.json
> +}
info 应包含的内容，应该有如下
```
info: {
      name: 'Three.extensionName',
      description: 'Three.description',
      extensionId: 'DilemmaGX.3dm',
      iconURL: Three_cover,
      insetIconURL: Three_icon,
      collaborator: 'David-Orangemoon@Github',
      collaboratorURL: 'https://github.com/David-Orangemoon',
    },
    l10n: {
      'zh-cn': {
        'Three.extensionName': '三',
        'Three.description': '从未感觉如此真实',
      },
      en: {
        'Three.extensionName': 'Three',
        'Three.description': 'Never considered to be such realistic',
      },
    }
```

2024-03-22 07:34 UTC, sylarhcn commented
@FurryR 非常好的 review ，使我周五的效率翻倍，晚上有空去约会。999 感恩
<img width="197" alt="image" src="https://github.com/Gandi-IDE/custom-extension/assets/1246288/55f5a3ba-d55e-47ae-95d6-ca95ad606fa2">

2024-03-22 07:35 UTC, merged