GamePad V1.0
Gandi-IDE/custom-extension pull request #209
Opened 2024-03-24 12:13 UTC by little-starts

feat(blcok):添加手柄拓展

2024-03-24 12:16 UTC, FurryR commented on wit_cat/GamePad.js
> +			let gp = this.getGamePad(args.num);
命名稍微有些奇怪... gamepad 是一个正确的英语名词，pad 无需首字母大写。

2024-03-24 12:17 UTC, FurryR commented on wit_cat/GamePad.js
> +	_addevent() {
命名应为 _addEvent。
p.s. 有个新实验语法可以将 # 开头的方法作为对象私有方法，所以也可以为 #addEvent。

2024-03-24 12:18 UTC, FurryR commented on wit_cat/GamePad.js
> +			id: witcat_sensory_control_extensionId, // 拓展id
命名请改为小驼峰。

2024-03-24 12:18 UTC, FurryR commented on wit_cat/GamePad.js
> +/** @typedef {string|number} SCarg 来自Scratch圆形框的参数，虽然这个框可能只能输入数字，但是可以放入变量，因此有可能获得数字和文本，需要同时处理 */
应为 `ScratchArg`

2024-03-24 12:19 UTC, FurryR commented on wit_cat/GamePad.js
> +navigator.vibrate = navigator.vibrate || navigator.webkitVibrate || navigator.mozVibrate || navigator.msVibrate;
不应当对全局对象进行不必要的污染，这可能会影响到其它的扩展。

2024-03-24 12:20 UTC, FurryR commented on wit_cat/GamePad.js
> +					return canvas.parentElement;
canvas 的 parentElement 不应当为 stage 么？

2024-03-24 12:21 UTC, Nightre commented
你厉害！！

2024-03-24 12:21 UTC, FurryR commented on wit_cat/GamePad.js
> +		this.canvasSelf = () => {
为什么它不能作为一个成员方法，而是要作为一个属性呢？

2024-03-24 12:22 UTC, FurryR commented on wit_cat/GamePad.js
> +		this._formatMessage = runtime.getFormatMessage({
（来自 HCN）getFormatMessage 不推荐使用，建议改为 Scratch.translate.setup 和 S cratch.translate，用法相同

2024-03-24 12:22 UTC, FurryR commented on wit_cat/GamePad.js
> +					blockType: 'Boolean',
应为 `Scratch.BlockType.BOOLEAN`

2024-03-24 12:24 UTC, FurryR commented on wit_cat/GamePad.js
> +					text: this.formatMessage('WitCatGamePad.axes'),
一次只能获取一个值，不应当是 `axis` 么？

2024-03-24 12:25 UTC, FurryR commented on wit_cat/GamePad.js
> +			"WitCatGamePad.descp": "牛逼外设！！！"
用词不雅

2024-03-24 12:25 UTC, FurryR commented on wit_cat/GamePad.js
> +			console.log(e);
对于送审的扩展，切勿随意 console.log，否则有可能导致 runtime 泄漏

2024-03-24 12:26 UTC, FurryR requested changes
非常好扩展，但是小问题有点多。已打回。

2024-03-24 13:38 UTC, little-starts commented
> i think this will render my tw ported gamepad extension useless, should i consider closing the pr in favour of this extension?

The main reason is that I waited too long for the gamepad, and I couldn't wait any longer, so I made it myself.

2024-03-25 00:49 UTC, little-starts commented on wit_cat/GamePad.js
> +navigator.vibrate = navigator.vibrate || navigator.webkitVibrate || navigator.mozVibrate || navigator.msVibrate;
兼容主流浏览器，这不算污染

2024-03-25 06:50 UTC, fath11 commented
you can prob add more blocks to it

2024-03-26 01:47 UTC, little-starts commented
> you can prob add more blocks to it

what blocks I can add?

2024-03-26 06:19 UTC, fath11 commented
> > you can prob add more blocks to it
> 
> what blocks I can add?

maybe some blocks from sharkpool's gamepad expanded https://sharkpools-extensions.vercel.app/

2024-03-29 08:22 UTC, sylarhcn reviewed
> i think this will render my tw ported gamepad extension useless, should i consider closing the pr in favour of this extension? 

Maybe you can merge two extension‘s block

2024-03-29 08:46 UTC, sylarhcn reviewed
凌的 review 并不是乱写的，都是言之有物的，如果有不同意见，可以直接回复原因在关闭（必须关于是否使用  axis 的复数形式），而不是无脑关闭。

客观一点

2024-03-29 09:08 UTC, little-starts commented
> 凌的 review 并不是乱写的，都是言之有物的，如果有不同意见，可以直接回复原因在关闭（必须关于是否使用 axis 的复数形式），而不是无脑关闭。
> 
> 客观一点

我回复了啊？
因为JS的API接口使用的是axes，我并没有重新翻译

2024-03-29 11:43 UTC, merged