pro
Gandi-IDE/custom-extension pull request #228
Opened 2024-04-10 15:04 UTC by bilioicik

test

2024-04-10 15:04 UTC, bilioicik commented
Finally, I know how to pr.

2024-04-10 15:11 UTC, bilioicik commented
Here are MotionPro and OperatorsPro. They have been done, but I can still improve them in some ways. And I plan to make more Pro after all.

2024-04-11 08:16 UTC, Arkos123 commented
![image](https://github.com/Gandi-IDE/custom-extension/assets/101853866/9dbe7829-78a9-4c5a-94bf-fed97e715892)
![image](https://github.com/Gandi-IDE/custom-extension/assets/101853866/83170a23-ead7-49e3-8dce-a034b15a0e56)
我不李姐这些积木的意义是什么（）
这个下拉菜单有点让人费解，另外true/false个人认为应该做成菱形积木
![image](https://github.com/Gandi-IDE/custom-extension/assets/101853866/2ee35269-66af-44de-bc11-6164e7a74358)
![image](https://github.com/Gandi-IDE/custom-extension/assets/101853866/0bbaf925-8beb-4a89-b293-be094618e870)
这些积木让人有点费解（比如作为原型，本质这些表达）很怪（）
![image](https://github.com/Gandi-IDE/custom-extension/assets/101853866/d89f9389-60c5-468f-bca1-f9463adae3d7)

2024-04-11 09:43 UTC, MoreBugOfDog commented
Oh, no! This is the same extension I already submitted for review! @bilioicik I already submitted this extension! Gotta close this PR or it will affect the reviewer's review.

2024-04-11 10:20 UTC, bilioicik commented
@Arkos123 就是注入了私有变量“移动速度”“移动方向”“转动速度”，为了表述简洁，我就写了两个字，不过这些在文档里交代清楚了。这样移动转动，省去了传参过程，对运行总是好的。

2024-04-11 10:33 UTC, bilioicik commented
@Arkos123 哦，你的“菱形积木”原来是这个意思。我以为你是说其他积木的圆形框。不过在条件的参数里塞定值本身就没有意义。这个积木主要作用是把字符串的“true”“false”这类转为真的布尔值的true、false，好push到数组对象。

2024-04-11 10:39 UTC, bilioicik commented
@Arkos123 （我知道对象不能用push函数，前一句说混在一起了）反正就是帮忙更改数组对象里的元素为true、false、undefined这种特殊类型值。扩展文档里有专门提及这个积木的用途。

2024-04-11 10:43 UTC, bilioicik commented
@MoreBugOfDog I know this, but I think pushing to my pr is more convernient because I still want to improve sth.

2024-04-11 10:44 UTC, bilioicik commented
@MoreBugOfDog I know this, but I think pushing to my pr is more convenient because I still want to improve something in my extensions.

2024-04-11 10:46 UTC, bilioicik commented
@MoreBugOfDog So that I don't need to disturb you again and again.

2024-04-13 12:41 UTC, bilioicik commented
@sylarhcn 我新开了一个请求，关于改良过的运动Pro和运算Pro，望过审。

2024-04-13 14:24 UTC, MoreBugOfDog commented
> 这样我就不需要一次又一次地打扰你了。
But you spelled my name wrong.
Correct:
多bug的啸天犬 @ CCW
Incorrect:
MoreBugOfDog @ CCW

2024-04-13 14:53 UTC, bilioicik commented
> > 这样我就不需要一次又一次地打扰你了。
> > But you spelled my name wrong.
> > Correct:
> > 多bug的啸天犬 @ CCW
> > Incorrect:
> > MoreBugOfDog @ CCW

All right. I think English username is cooler. Actually, 凌 use FurryR in his extension.

2024-04-13 14:54 UTC, bilioicik commented
> > But you spelled my name wrong.
> > Correct:
> > 多bug的啸天犬 @ CCW
> > Incorrect:
> > MoreBugOfDog @ CCW

All right. I think English username is cooler. Actually, 凌 used FurryR in his extension.

2024-04-13 14:57 UTC, bilioicik commented
@MoreBugOfDog I will change it tomorrow.

2024-04-13 14:58 UTC, bilioicik commented
@MoreBugOfDog So maybe you need to close your pr. Do you want to make more changes in OperatorsPro?

2024-04-15 07:08 UTC, fath11 commented
Please create your own folder and put the extensions in that folder
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/6b18e844-b429-4089-a4d8-d3c62e6e14be)

2024-04-15 07:24 UTC, fath11 commented
Doing this is terrible; I prefer the old version of this extension 
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/6363aeae-88dd-4af2-917d-ee9f9705147c)

This will force the user to set the movement speed, etc., with another block before being able to move. In typical projects, the speed will stay the same, but with more advanced projects, such as a custom 3D renderer or projects that need to do a lot of heavy calculations, not being able to input values to blocks directly will significantly impact performance.

2024-04-17 10:40 UTC, bilioicik commented
@fath11 The old blocks of this extension are still here. To avoid clutter, they are hidden. Press the second button then you can see them. 
These new blocks can be used in many different ways. If the types of their arguments are NUMBER, they will directly use the values which you put. You can also put variables'names or id there, they will find the variables you want.

2024-04-17 11:08 UTC, bilioicik commented
@fath11 OK, I created my own folder just now.

2024-04-17 12:33 UTC, fath11 commented
movement speed, movement direction, and rotation angle are all just variables. There is no reason to make the block palate bigger. It is cool to have togglable blocks, but why try to hide the clutter when the clutter can be removed?

2024-04-18 10:48 UTC, bilioicik commented
@fath11 The old blocks are more useful for their running speed because they do not recognize types of values. So I don’t want to remove them. But the number of them is plenty big. It’s bad for editing. Users won’t feel good. So l add them together to new blocks.

2024-04-21 09:08 UTC, bilioicik commented
![image](https://github.com/Gandi-IDE/custom-extension/assets/164740037/821a27c5-643a-4e3a-b491-6eacbedd09bb)
@fath11 Would you like this? I made blocks shorter and easy to understand.

2024-04-21 12:31 UTC, bilioicik commented
@sylarhcn @fath11 请核审

2024-04-21 12:31 UTC, bilioicik commented
@sylarhcn @fath11 请核审

2024-04-23 08:05 UTC, fath11 commented
> ![image](https://private-user-images.githubusercontent.com/164740037/324235836-821a27c5-643a-4e3a-b491-6eacbedd09bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTkyODYsIm5iZiI6MTcxMzg1ODk4NiwicGF0aCI6Ii8xNjQ3NDAwMzcvMzI0MjM1ODM2LTgyMWEyN2M1LTY0M2EtNGUzYS1iNDkxLTZlYWNiZWRkMDliYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QwNzU2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2NlOGQ4ZGY5MDBjOTU4Y2FkYTU5ZTZjNmEzYmUzMTNiZGRjNTgyZmU4ZmVhZThiNmI3YWViNTNjZmIwMTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U8qO--6tLNtOaiGvk_dpqqOMmT-4xUymIYQYZCf1R80) @fath11 Would you like this? I made blocks shorter and easy to understand.

The use case for variables is really small. There are other kind of variables from other extensions. Implementing and maintaining support for every single kind of variables in every extensions is impossible. Sure you can just drop the reporter of that variable into any of the blocks and it works just fine, but then you might as well use normal blocks with normal input parameters.

You need to make a compromise between minor performance increase and usableness/not making the block palette uselessly large and **the extension's code uselessly complicated to maintain**.

2024-04-24 12:09 UTC, bilioicik commented
It’s hard for me to choose one. Well, in my opinion, it’s ok to have both. I have made several tests to make sure there’s no bug in this extension. All of the blocks can work properly and are easy to use. On one hand, it is true that we can use Scratch blocks to achieve some similar aims. On the other hand,this will let very young and new Scratchers do it easily. Don’t we have a section called “Beginners”? It is reasonable to let beginners use it. Maybe some of them like using single menu blocks, others want to have better running speed. Perhaps it’s not necessary to create some blocks, but it’s more unnecessary to remove them. I think no one among ordinary users will refuse to have more choices.

By the way, I have expected for a long time. It will make me mad to go on to change it during Grade 9 such a busy term. Of course, it’s because of my poor experience.

2024-04-24 12:16 UTC, fath11 commented
How about make a button to switch between both kind of blocks instead of how it is right now. So only one kind of the block will appear at any one time and the rest are hidden

2024-04-24 12:51 UTC, bilioicik commented
About the variable menu, if users have the same advice as yours, I will take it at once. Only the type of the argument will be changed. No problem with the value. So you don’t need to worry about the changing after it is public will cause bad influence. And you don’t need to pay attention to this before it is public.

2024-04-24 12:57 UTC, bilioicik commented
I tried to make a button like that before, but it seems that there’s a bug in Gandi. “! variable”in blocks will cause ERROR.

2024-04-24 13:09 UTC, bilioicik commented
I mean, the method like “hidefrompallette: ! this.hideextrablocks”.

2024-04-24 13:31 UTC, bilioicik commented
“hidefrompallette: ! this.hideextrablocks” in blocks doesn’t work . Strangely, “hidefrompallette: ! this.hideextrablocks” in buttons always works.

2024-04-24 23:47 UTC, fath11 commented
split the blocks into two arrays, when the button is pressed, switch which array is being given to the blocks property and refresh the block palette

2024-04-25 14:02 UTC, bilioicik commented
Ok, I have done it. But in other ways.

2024-05-02 04:22 UTC, bilioicik commented
@sylarhcn Please review.

2024-05-08 14:04 UTC, MoreBugOfDog reviewed
可以看一下我对链接美化的建议，这是我的个人喜好，非必须

2024-05-08 14:04 UTC, MoreBugOfDog commented on bilioicik/OperatorsPro
> link:   https://ccw.site/student/{{oid}}  =>  https://ccw.site/student/{{uid}}

这样会更好？
缩短了链接长度，但这不是必须的，我个人认为uid比乱码id更好看些
示例
>link:   https://www.ccw.site/student/6200811f05660557606c8b15  => https://www.ccw.site/student/197354885

2024-05-11 10:18 UTC, sylarhcn requested changes
1. 文件使用正确的后缀
2. 一个 pr 请只包含一个扩展的修改，
3. 过于复杂的扩展，请在 pr 详情中，写明扩展的设计目的和积木的功能，积木可以使用截图，这样能更好的被讨论与审核

2024-05-11 10:18 UTC, sylarhcn commented on bilioicik/ControlPro
> +            ! [0,false,undefined,null,'','0','false','undefined','null'].includes(a)
这种数组你应该定义为静态的常量来使用

2024-05-11 11:17 UTC, bilioicik commented
改了后缀，正在研究怎么分开交，我前面新开了个ControlPro，但之前的内容意外出现在那儿的commits里了。

2024-05-11 11:21 UTC, sylarhcn commented
> 改了后缀，正在研究怎么分开交，我前面新开了个ControlPro，但之前的内容意外出现在那儿的commits里了。

那我先关闭这个 pr。
你可以开多个开发分支，然后单独 pr 就可以。
最后你在合并的开发分支就行了。

2024-05-11 11:56 UTC, bilioicik commented
![image](https://github.com/Gandi-IDE/custom-extension/assets/164740037/88fb7ff7-de21-4f7b-b148-3322162e3212)
![21e6c4067fece829d5827bdb7416de12](https://github.com/Gandi-IDE/custom-extension/assets/164740037/e88a5e82-9ce6-4e2a-a792-b48947f7da60)

用多个branch不太明白，我想应该是新创建一个branch，但情况咋跟这教程不太一样呢…

2024-05-11 11:57 UTC, bilioicik commented
我打算先把其他文件删了保留一个

2024-05-11 12:41 UTC, closed without merging