渲染世界扩展(RenderTheWorld)的提交
Gandi-IDE/custom-extension pull request #232
Opened 2024-04-14 10:01 UTC by xiaochen004hao

<div align="center">
  
# 😎 渲染世界扩展

> Scratch 3D扩展.

</div>
<br>
<br>
<div align="center"><h2>

```
按照要求进行了更改 / 使用了凌提供的脚手架
```

</h2></div>

2024-04-14 10:05 UTC, xiaochen004hao commented
请在第`26232`行查看主程序，前面的是库

2024-04-15 12:32 UTC, qxsck commented
docs可以用
`docsURI:'https://learn.ccw.site/article/e6ba96d6-17a4-4f63-b5e1-126acbbb82d4',`，在getInfo里

2024-04-20 01:19 UTC, FurryR commented
错误的使用方式。请另开仓库，并在仓库中提交你的更改，然后将编译后的产物提交到 Gandi 仓库，并注上原仓库。

2024-04-20 03:15 UTC, xiaochen004hao commented
> 错误的使用方式。请另开仓库，并在仓库中提交你的更改，然后将编译后的产物提交到 Gandi 仓库，并注上原仓库。

有点懵

2024-04-27 10:23 UTC, xiaochen004hao commented
# 谁能讲讲怎么控制并自己绘制舞台的外观呢？

2024-04-27 13:41 UTC, xiaochen004hao commented
我觉得我很难阅读lpp很大原因是因为我英语不是很好（小学水平）。。。

2024-04-28 04:06 UTC, fath11 commented
i dont think i can review this extension lol. My computer cant load it at all.

2024-04-28 10:18 UTC, xiaochen004hao commented
> 我想我不能审查这个扩展哈哈。我的电脑根本无法加载它。

额，我可能pr了一个错误的版本，5月1日的时候看看

2024-05-03 14:09 UTC, xiaochen004hao commented
谁能教教我替换舞台区的绘制啊？急急急（因为这样HCN说不定就能过审了）

2024-05-11 10:22 UTC, sylarhcn requested changes
<img width="812" alt="image" src="https://github.com/Gandi-IDE/custom-extension/assets/1246288/66a7e7fd-32a2-4591-a511-9f9b433a78b5">

审核不能...

2024-05-12 08:04 UTC, fath11 commented
at this point, i think you should just PR the old version that is not made with furryr's scaffolding 💀

2024-05-14 10:57 UTC, xiaochen004hao commented
> <img alt="image" width="812" src="https://private-user-images.githubusercontent.com/1246288/329773587-66a7e7fd-32a2-4591-a511-9f9b433a78b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODQ1MDIsIm5iZiI6MTcxNTY4NDIwMiwicGF0aCI6Ii8xMjQ2Mjg4LzMyOTc3MzU4Ny02NmE3ZTdmZC0zMmEyLTQ1OTEtYTUxMS05ZjliNDMzYTc4YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTA1NjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjgwM2MzOTVkNTE1ODhhNzgyNTg0YmNiOTJkZjJjMzFlZDlkNzQyZjNmZGU5ZWZmMDE3ODA0NWE4NWI3Mzc2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XPpv5Ru8SI2ZbqQdWFZk1JmFy02zIL5xooa6QkwPoag">
> 审核不能...

请点击文件右上角的“...”，再点击“View file”
https://github.com/Gandi-IDE/custom-extension/blob/738218b4b894e5227f629b2b5c6425662a2aa51b/RenderTheWorld/RenderTheWorld.js

2024-05-20 10:28 UTC, xiaochen004hao commented
> 由于你提交的代码过大，你可以在 pr 描述中，补充一下以下内容吗，或者给你的扩展加个 readme
> 
> 1. 扩展的设计目标，为了解决什么问题
> 2. 扩展积木的数量及他们 分类
> 3. 所有扩展积木的截图
> 4. 扩展的使用方式效果描述（有视频就更好了）

为什么不能在周六回复我。。。只能这周六搞了

2024-05-20 11:02 UTC, sylarhcn commented
> > 由于你提交的代码过大，你可以在 pr 描述中，补充一下以下内容吗，或者给你的扩展加个 readme
> > 
> > 1. 扩展的设计目标，为了解决什么问题
> > 2. 扩展积木的数量及他们 分类
> > 3. 所有扩展积木的截图
> > 4. 扩展的使用方式效果描述（有视频就更好了）
> 
> 为什么不能在周六回复我。。。只能这周六搞了

1.因为上周六我生病了
2.因为周六是周末

2024-05-21 10:37 UTC, xiaochen004hao commented
> > > 由于你提交的代码过大，你可以在 pr 描述中，补充一下以下内容吗，或者给你的扩展加个 readme
> > > 
> > > 1. 扩展的设计目标，为了解决什么问题
> > > 2. 扩展积木的数量及他们 分类
> > > 3. 所有扩展积木的截图
> > > 4. 扩展的使用方式效果描述（有视频就更好了）
> > 
> > 
> > 为什么不能在周六回复我。。。只能这周六搞了
> 
> 1.因为上周六我生病了 2.因为周六是周末

（这里应该没有学生党歧视吧）这个学期我只能周六用电脑

2024-05-25 07:19 UTC, xiaochen004hao commented
现在有README.md了，不过在PR描述中也能看

2024-06-20 09:48 UTC, fath11 commented
you should use `renderer.setAnimationLoop( () => {renderer.render(scene, camera)} )` to render the scene instead of just using `renderer.render(scene, camera)`. this will remove the need of a special render block AND make the rendering significantly faster

an example use is as follow:
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/f1ecb7da-5760-4ea6-a3cf-764bb541008c)
this is a function for a block to rotate a cube
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/100fd11f-c746-4c25-9816-5d427c1998ea)

the main problem i have with this extension is how laggy it is, but using this method should remove all the lags

2024-06-20 10:35 UTC, xiaochen004hao commented
> 你应该用 `renderer.setAnimationLoop( () => {renderer.render(scene, camera)} )` 来渲染场景，而不是仅仅使用 `renderer.render(scene, camera)`.这将消除对特殊渲染块的需要，并使渲染速度显著加快
> 
> 一个示例用法如下： ![image](https://private-user-images.githubusercontent.com/124476952/341363880-618eef7a-a70f-4508-8643-b0a270c4d5e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Nzk4NTYsIm5iZiI6MTcxODg3OTU1NiwicGF0aCI6Ii8xMjQ0NzY5NTIvMzQxMzYzODgwLTYxOGVlZjdhLWE3MGYtNDUwOC04NjQzLWIwYTI3MGM0ZDVlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxMDMyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjIwMDJkNTk4N2VlMTBkZjY5ZWJkYWM2ODRhM2EwMDgyYTBmYzA2ZDU2MjRkZjM5ODkwZDQ1OGE3NmMwY2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N_jlcIPmqHd9apmkMuxLbVPfS9qyoWisp_hi-sN0Enw) 这是一个用于块旋转立方体的函数 ![image](https://private-user-images.githubusercontent.com/124476952/341362139-100fd11f-c746-4c25-9816-5d427c1998ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Nzk4NTYsIm5iZiI6MTcxODg3OTU1NiwicGF0aCI6Ii8xMjQ0NzY5NTIvMzQxMzYyMTM5LTEwMGZkMTFmLWM3NDYtNGMyNS05ODE2LTVkNDI3YzE5OThlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxMDMyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGI5NDE2YjZjMTFmMTJhNzVlYjFmZTA1MTBkYzA3NTQwYWVmMDlhNDIxNTcxYWY1N2Q1YjZjYzU3N2U4YjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BBjB2DCFDH-inDNvog6U2JbFYY-HfRlqXJtKRwMPBNk)
> 
> 我对这个扩展的主要问题是它的滞后性，但使用这个方法应该可以消除所有的滞后性

这我的确知道，不过。。。
我懂该怎么做了，不过最近可能不能提交更改（升学考试）

2024-06-21 01:18 UTC, fath11 commented
> 这我的确知道，不过。。。 我懂该怎么做了，不过最近可能不能提交更改（升学考试）

no worries, ill make a pr to your original project and this project so you just have to merge my changes
```js
this.render = () => {
          if (!this.tc) {
            return "\u26A0\uFE0F\u663E\u793A\u5668\u672A\u521D\u59CB\u5316\uFF01";
          }
          this._clock = this.clock.getDelta();
          this.renderer.render(this.scene, this.camera);
          if (this.controls.enableDamping) {
            this.controls.update();
          }
        }
        this.renderer.setAnimationLoop(this.render)
```

2024-06-25 11:13 UTC, fath11 commented
also i forgot to mention that this snippet of code will cause a warning if you run the `init` block multiple times because you reached the maximum listener count. so you need to find a way to define the listener only once in RenderTheWold's constructor
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/774df269-0d6b-4999-ae7d-ae9f5d109f9a)

2024-07-12 07:45 UTC, fath11 commented
good news! Todo 5 will be resolved soon
![image](https://github.com/user-attachments/assets/0f0addf1-61be-4814-a2d6-2308563cd49f)

for anyone interested: https://github.com/xiaochen004hao/RenderTheWorld/pull/4

2024-07-14 10:49 UTC, closed without merging