Zip V1.0
Gandi-IDE/custom-extension pull request #244
Opened 2024-05-15 05:50 UTC by little-starts

feat(block):增加zip处理拓展
feat(block):[文件助手]通过指定方式打开上次打开的拓展
feat(block):[文件助手]通过blob URL下载文件

2024-05-20 10:41 UTC, sylarhcn commented
‘feat(block):[文件助手]通过指定方式打开上次打开的拓展’

这是啥功能，可以具体描述一下吗

2024-05-20 10:43 UTC, sylarhcn requested changes

2024-05-20 10:43 UTC, sylarhcn commented on wit_cat/File_Helper.js
为啥这个文件会有更新，你是一次提交两个扩展吗？

如果是，你需要分一下，保证一个 pr 只有一个扩展

2024-05-20 11:13 UTC, little-starts commented on wit_cat/File_Helper.js
打开上次打开的是从上次打开的信息的升级，支持读取为zip格式，原积木只支持读取为UTF-8
更新的是文件助手和zip联动的部分，文件助手没有更新，如果不同时更新，zip将不支持打开和下载

2024-06-12 06:46 UTC, sylarhcn commented on wit_cat/Zip/dist/Zip_dev.js
你带源码的提交的话，一般不需要提交 dist 文件夹，因为使用这个源码的人可以自己编译。
我更新一下 gitignore

2024-06-12 08:02 UTC, merged