witcat ext 2.0 新增积木，功能，优化功能，修复错别字
Gandi-IDE/custom-extension pull request #65
Opened 2023-02-07 01:51 UTC by little-starts

//More_Mouse
feat(block):修改鼠标指针样式系列积木
perf(block):锁定鼠标可以选择释放
fix(block):电脑端模拟触摸屏按下无响应的问题
//Input
feat(block):获取，设置文本框透明度
feat(block):获取，设置文本框的滚动位置
feat(block):获取文本框文本高度
feat(block):获取，设置文本框的光标位置
fix(block):修复英文the写成teh的错误

2023-02-09 12:47 UTC, sylarhcn requested changes

2023-02-09 12:47 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +				"WitCatMouse.mouseuse": "[mouseuse]鼠标",
这个地方把原来的非菜单改为了菜单,会有兼容性bug吗

2023-02-09 12:47 UTC, sylarhcn commented on wit_cat/More_Mouse.js
>  document.onmousedown = event => {
应该使用 addEventListener 而不是直接赋值

2023-02-09 13:16 UTC, little-starts commented on wit_cat/More_Mouse.js
> +				"WitCatMouse.mouseuse": "[mouseuse]鼠标",
新版更新后复制/拖出来的积木支持锁定和解锁，但是更新前就存在的效果与旧版一致

2023-02-11 07:39 UTC, sylarhcn approved these changes

2023-02-11 07:39 UTC, merged