:sparkles: 添加 FurryR/not.js
Gandi-IDE/custom-extension pull request #69
Opened 2023-02-19 11:54 UTC by FurryR

关于 Not.js 的更多信息，请参见 [Not.JS GitHub](https://github.com/FurryR/not.js) 或 [共创世界教程](https://www.ccw.site/post/9cb88c31-c4eb-4244-a412-625e33ca6882)。

2023-02-21 13:27 UTC, sylarhcn reviewed
感觉每次读写都要 stringify 一下可能会有潜在的问题。
因为看起来你的设计，是想在 scr 中模拟对对象中变量的读写？如果是这样的话，那这种读写肯定是高频的。 频繁的 stringify 肯定会导致性能问题，特别是如果 json 对象很大的情况下。

其他疑问都是 comment 在对应行上了

2023-02-21 14:48 UTC, FurryR commented on FurryR/not.js.js
> +    const v = this._parseJSON(args.json)[0]
举个例子。
解析 `{"a": 1, "b": 2}` = `{"a":1,"b":2}`
所以一定有存在的必要。

2023-02-21 14:50 UTC, FurryR commented on FurryR/not.js.js
> +    this._container.set(str, value)
实际上，仔细读一下就知道有时候还是要用到键的。甚至，在部分地方还会直接使用 key 缓存。

2023-02-21 15:03 UTC, FurryR commented on FurryR/not.js.js
> +    const str = JSON.stringify(value)
1. 老式的 json 处理库也需要 stringify，没得说。
2. cache 缓存键，这样在部分操作时可以直接用到缓存，这样反而少一些 stringify。此外，stringify 是只有在新的对象被解析时才会发生的。
3. 要避免的是 parse 而 stringify 可以适当使用，因为 parse 时对象所需的内存比较多，而 stringify 反而较少。我写过半个 JSON 解析库，stringify 的速度是比 parse 要快的。

2023-02-22 02:05 UTC, sylarhcn commented on FurryR/not.js.js
> +    const str = JSON.stringify(value)
1，3 我都理解，没问题的。
2，我还是有个疑问，从代码看这里不是所有的 value 都会 stringify 吗（undefined除外）。“stringify 是只有在新的对象被解析时才会发生的”，我没有理解。是指其实在外部使用中，有部分 value 早就已经是 string 了？ 比如之前命中过缓存并返回的？ 是这个意思吗？

2023-02-22 02:09 UTC, sylarhcn commented on FurryR/not.js.js
> +    this._container.set(str, value)
之所以我说我们语音会 review 更快，就是因为我没那么多时间全部细读🥹。只能晚上加班看 pr ...
如果你测试后觉得可以接受的，我是没有问题的。

2023-02-22 02:46 UTC, sylarhcn commented
另外，extensionID，你考虑加上你自己的 namespace 吗，这样的话个人标识强一点，也不容易重名。

2023-02-22 02:52 UTC, six-ddc commented on FurryR/not.js.js
> +          opcode: 'fromString',
fromString 意思是将 `hello` 转换成 `"hello"` 吗？

2023-02-22 14:02 UTC, FurryR commented
> 另外，extensionID，你考虑加上你自己的 namespace 吗，这样的话个人标识强一点，也不容易重名。

好的，我到时候再加，并且我要加个 TTL 机制。
在添加完成之前我会先暂时将这个 pr 变更为草案，请不要提交。

2023-02-26 15:07 UTC, FurryR commented
我犯了一个设计错误——cache 在 Javascript 下快，Scratch 下慢。
目前已经修正文档，将 Not.js 作为 CCWData 的更安全 & 更完备的版本使用。

2023-02-28 15:10 UTC, sylarhcn requested changes
我才发现直接提交打包的后的代码时不行的。
因为旧模版的发布机制是手动的，扩展注册目录和扩展 class 做了分离。
你打包后的代码，因为找不到基础信息和class入口，我就没法发布了。

2023-02-28 15:10 UTC, sylarhcn requested changes
我才发现直接提交打包的后的代码时不行的。
因为旧模版的发布机制是手动的，扩展注册目录和扩展 class 做了分离。
你打包后的代码，因为找不到基础信息和class入口，我就没法发布了。

2023-02-28 23:05 UTC, FurryR commented
> 我才发现直接提交打包的后的代码时不行的。 因为旧模版的发布机制是手动的，扩展注册目录和扩展 class 做了分离。 你打包后的代码，因为找不到基础信息和class入口，我就没法发布了。

已修复。

2023-03-01 02:07 UTC, merged