witcat ext 2.3 更新 修复
Gandi-IDE/custom-extension pull request #72
Opened 2023-03-11 14:38 UTC by little-starts

//全部
perf(compile):修改打开文档的按钮为button，使用新窗口而非原本的重定向
//文件助手
feat(block):上传，下载图片（base64）
feat(block):获取base64图片的宽高
feat(block):压缩base64图片
fix(block):修复文字base64在非base64下报错的BUG
//文本框
feat(block):设置，获取背景图片
fix(compile):修复通过颜色修改css的BUG
//高级鼠标
feat(block):增加判断鼠标点击，双击
fix(compile):修复ico转base64概率报错
fix(compile):修复鼠标设置ico图片时错误base64循环报错的BUG

2023-03-11 17:05 UTC, FurryR commented
能 close 尽 close。这样玩等同于和 clipcc multilines 彻底决裂。

2023-03-12 15:15 UTC, little-starts commented
文件助手更新了键值对，保存在一个免费的云端

2023-03-14 12:57 UTC, little-starts commented
> 能 close 尽 close。这样玩等同于和 clipcc multilines 彻底决裂。

本来就是两个拓展，何来决裂一说？

2023-03-14 13:00 UTC, kukemc commented
> 能 关闭 尽 关闭。这样玩等同于和 clipcc multilines 彻底决裂。

要不要看看你在说什么？，两个独立的扩展决裂是吧

2023-03-15 13:30 UTC, FurryR commented
> > 能 关闭 尽 关闭。这样玩等同于和 clipcc multilines 彻底决裂。
> 
> 要不要看看你在说什么？，两个独立的扩展决裂是吧

对啊，但是你现在删掉这个特性，clipcc 那边用到这个特性的就难移植了。

2023-03-15 13:31 UTC, FurryR commented on wit_cat/Input.js
> +				return search.style.backgroundImage.split("\"")[1];
你连 JSON.parse 都不愿意用，我真的哭死。

2023-03-15 13:33 UTC, FurryR commented on wit_cat/Input.js
> +			let dom = `background-color: transparent;border:0px;text-shadow: 0 0 0 #000;outline: none;position:absolute; left:` + x + `%; top:` + y + `%; width:` + width + `%; height:` + height + `%;font-size
我该怎么说呢...

2023-03-15 14:37 UTC, little-starts commented on wit_cat/Input.js
> +				return search.style.backgroundImage.split("\"")[1];
写这个时还不会这个，所以一个个敲的

2023-03-15 14:38 UTC, little-starts commented on wit_cat/Input.js
> +		let dom = `background-color: transparent;border:0px;text-shadow: 0 0 0 #000;outline: none;position:absolute; left:` + x + `%; top:` + y + `%; width:` + width + `%; height:` + height + `%;font-size:
谢谢

2023-03-15 14:38 UTC, little-starts commented on wit_cat/Input.js
> +			let dom = `background-color: transparent;border:0px;text-shadow: 0 0 0 #000;outline: none;position:absolute; left:` + x + `%; top:` + y + `%; width:` + width + `%; height:` + height + `%;font-size
你也可以不说

2023-03-16 14:23 UTC, little-starts commented
> > > 能 关闭 尽 关闭。这样玩等同于和 clipcc multilines 彻底决裂。
> > 
> > 要不要看看你在说什么？，两个独立的扩展决裂是吧
> 
> 对啊，但是你现在删掉这个特性，clipcc 那边用到这个特性的就难移植了。

不考虑移植吧，本来就是两个社区

2023-04-28 03:37 UTC, sylarhcn requested changes

2023-04-28 03:37 UTC, sylarhcn commented on wit_cat/Input.js
> +					onClick: this.docs,
文档可以直接使用 docsURI 配置，不用自己做 button

2023-04-28 03:37 UTC, sylarhcn commented on wit_cat/Input.js
> +		let sstyle = search.style;
sstyle 这种变量名太不可读了。。。

2023-04-28 03:37 UTC, sylarhcn commented on wit_cat/Input.js
> +		let sstyle = search.style;
建议可以学习代码规范相关的基础

2023-04-28 03:37 UTC, sylarhcn commented on wit_cat/IndexedDB.js
> +showButton();
不允许未经用户操作的默认注入操作

2023-04-28 03:37 UTC, sylarhcn commented on wit_cat/More_Mouse.js
>  function base64ImgtoFile(dataurl, filename = 'file') {
这里看起来应该使用你的 base64.js 来处理？

2023-04-28 03:37 UTC, sylarhcn commented on wit_cat/IndexedDB.js
> +let interval = setInterval(() => {
这个 interval 永远不停止？

2023-04-28 03:37 UTC, sylarhcn commented on wit_cat/IndexedDB.js
> +    numbers() {
废弃函数，但是函数实现还是有？

2023-04-28 03:37 UTC, sylarhcn commented on wit_cat/IndexedDB.js
> +    numbers() {
numbers 这个命名也不好，什么的numbers？

2023-04-28 03:37 UTC, sylarhcn commented on wit_cat/IndexedDB.js
> +    showvaro(args) {
camel-case

2023-04-28 03:37 UTC, sylarhcn commented on wit_cat/IndexedDB.js
> +function SSetKey(name, text, content, h, state, id, description) {
SSetKey 这个命名也有点意义不明

2023-04-28 03:37 UTC, sylarhcn commented on wit_cat/IndexedDB.js
> +function SetKeys({ name, text, content, h, state, id, description }, recall) {
SSetKey 与 SetKeys 不能从名字上看出却别，代码维护和阅读难度大

2023-04-28 23:02 UTC, little-starts commented on wit_cat/FPS.js
> +                    onClick: this.docs,
不直接配置是因为你们docsURI是直接重定向，而我想要的效果是新页面。
有时候没保存作品，你们直接重定向，很崩溃...

2023-04-28 23:02 UTC, little-starts commented on wit_cat/FPS.js
> +                    onClick: this.docs,
而且你们按钮没有中文，全是英文

2023-04-28 23:08 UTC, little-starts commented on wit_cat/IndexedDB.js
> +showButton();
注入是为了用户能管理键值对，可以自己关闭，不会再弹出来。

2023-04-28 23:08 UTC, little-starts commented on wit_cat/IndexedDB.js
> +function SetKeys({ name, text, content, h, state, id, description }, recall) {
加注释就行了

2023-05-02 01:06 UTC, 9-2-1 commented on wit_cat/IndexedDB.js
> +    numbers() {
我写的注释，他更新代码。导致注释维护和代码维护不一致。

2023-05-02 01:10 UTC, 9-2-1 commented on wit_cat/FPS.js
> +const _picture = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAeAAAAEPCAYAAACaxhfCAAB96UlEQVR42u29a6xsyXUXvmp3n3Mfc+fOyzMee2b8iGywMUiWDJYJxDySCARI5Fu+IWQ+8AEhpAj+YATIQsBHHiZISJbAyl8IESGBgvIPwR9QghL
> 图片资源，你同时可以提交一个对应的图片文件。 这样在我发布时，我可以直接使用文件，不需要 base64，因为我发布后不会有跨域问题。
> 
> 这里用 base64 主要是方便你测试，因为你测试的时候可能会有跨域的访问的问题，导致图片文件读取不到。

这个烂操作是我在 DateTime 开始的。问题不是测试的时候跨域，而是测试的时候，图片的 URL 如果写成相对就会相对于网页，额不是相对于扩展 JS，因此无法引用。

2023-05-02 03:26 UTC, 9-2-1 commented on wit_cat/FPS.js
> +                    onClick: this.docs,
gandi 页面的 window.open 被不知哪里的挂钩修改了，原本的 window.open 是打开新窗口的，在 gandi 页面调用 window.open 会直接重定向。用 F12 会发现 window.open 被覆盖了

2023-05-02 03:26 UTC, 9-2-1 commented on wit_cat/IndexedDB.js
> +    numbers() {
> 废弃函数，但是函数实现还是有？

我写的注释，他更新代码。导致注释和代码不一致。

2023-05-25 01:39 UTC, closed without merging