:sparkles: Sync from FurryR/not.js
Gandi-IDE/custom-extension pull request #73
Opened 2023-03-15 12:59 UTC by FurryR

# 更新
- 扔掉了 fromBoolean 这个鸡肋功能。

没别的了。

2023-03-16 14:34 UTC, little-starts requested changes
不建议直接删除这个积木，会导致积木变成红色积木块。
最好的做法是在block里改hide属性为true，然后删掉执行的函数。
这是为了能够更好的向下兼容

2023-03-20 00:58 UTC, 9-2-1 commented
> 不建议直接删除这个积木，会导致积木变成红色积木块。 最好的做法是在block里改hide属性为true，然后删掉执行的函数。 这是为了能够更好的向下兼容

额，不应该是“不删掉”执行的函数么

还可以学习mmo写一个“X 弃用的积木”

2023-03-20 09:35 UTC, sylarhcn requested changes
1. 不建议删除已经上线的积木 - 会导致使用过的作品无法打开
2. 过时的积木，可以使用 hideFromPalette: true, 在 toolBox 中隐藏
3. 可以修改过时积木的 text ，提醒在使用的人替换

2023-03-20 11:45 UTC, little-starts commented
> > 不建议直接删除这个积木，会导致积木变成红色积木块。 最好的做法是在block里改hide属性为true，然后删掉执行的函数。 这是为了能够更好的向下兼容
> 
> 额，不应该是“不删掉”执行的函数么
> 
> 还可以学习mmo写一个“X 弃用的积木”

我是指删掉对应的代码，不是删除函数，我可能说的有点问题，抱歉

2023-03-20 13:16 UTC, FurryR commented
> 1. 不建议删除已经上线的积木 - 会导致使用过的作品无法打开
> 2. 过时的积木，可以使用 hideFromPalette: true, 在 toolBox 中隐藏
> 3. 可以修改过时积木的 text ，提醒在使用的人替换

不采用。
1. 截至目前为止尚未发现有人使用这个积木。
2. 考虑这个插件目前还在 **Beta** 阶段，有任何（不兼容）变更都在合理的范围之内。上述处理应该在插件进入 **Release** 阶段以后才考虑。
3. 修复方法极易，删掉这个积木，改为直接用布尔值即可。

2023-03-20 15:22 UTC, 9-2-1 commented
> > 1. 不建议删除已经上线的积木 - 会导致使用过的作品无法打开
> > 2. 过时的积木，可以使用 hideFromPalette: true, 在 toolBox 中隐藏
> > 3. 可以修改过时积木的 text ，提醒在使用的人替换
> 
> 不采用。
> 
>     1. 截至目前为止尚未发现有人使用这个积木。
> 
>     2. 考虑这个插件目前还在 **Beta** 阶段，有任何（不兼容）变更都在合理的范围之内。上述处理应该在插件进入 **Release** 阶段以后才考虑。
> 
>     3. 修复方法极易，删掉这个积木，改为直接用布尔值即可。

有可能已经有用户使用了这个积木并且保存在了私有作品内，只是没有看到  
删除该积木将会导致这类作品打开后丢失相关积木（与积木连接地相关积木都会受影响），甚至全局报错，无法*正常*编辑，更别说进行修复。就算最好情况只有这个积木消失留下空格，也会给作品的调试带来影响

2023-03-23 14:28 UTC, FurryR commented
> > > 1. 不建议删除已经上线的积木 - 会导致使用过的作品无法打开
> > > 2. 过时的积木，可以使用 hideFromPalette: true, 在 toolBox 中隐藏
> > > 3. 可以修改过时积木的 text ，提醒在使用的人替换
> > 
> > 
> > 不采用。
> > ```
> > 1. 截至目前为止尚未发现有人使用这个积木。
> > 
> > 2. 考虑这个插件目前还在 **Beta** 阶段，有任何（不兼容）变更都在合理的范围之内。上述处理应该在插件进入 **Release** 阶段以后才考虑。
> > 
> > 3. 修复方法极易，删掉这个积木，改为直接用布尔值即可。
> > ```
> 
> 有可能已经有用户使用了这个积木并且保存在了私有作品内，只是没有看到 删除该积木将会导致这类作品打开后丢失相关积木（与积木连接地相关积木都会受影响），甚至全局报错，无法_正常_编辑，更别说进行修复。就算最好情况只有这个积木消失留下空格，也会给作品的调试带来影响

仍然不采用。
1. 这个项目是 Beta 版，不是 Release 版，更何况是第一版，我没必要做前向兼容。
2. 拖泥带水地删除一个功能只会导致维护问题。
3. 好比 Python 2 到 Python 3，干净利落。

2023-03-23 23:57 UTC, six-ddc commented
> > > > 1. 不建议删除已经上线的积木 - 会导致使用过的作品无法打开
> 
> > > > 2. 过时的积木，可以使用 hideFromPalette: true, 在 toolBox 中隐藏
> 
> > > > 3. 可以修改过时积木的 text ，提醒在使用的人替换
> 
> > > 
> 
> > > 
> 
> > > 不采用。
> 
> > > ```
> 
> > > 1. 截至目前为止尚未发现有人使用这个积木。
> 
> > > 
> 
> > > 2. 考虑这个插件目前还在 **Beta** 阶段，有任何（不兼容）变更都在合理的范围之内。上述处理应该在插件进入 **Release** 阶段以后才考虑。
> 
> > > 
> 
> > > 3. 修复方法极易，删掉这个积木，改为直接用布尔值即可。
> 
> > > ```
> 
> > 
> 
> > 有可能已经有用户使用了这个积木并且保存在了私有作品内，只是没有看到 删除该积木将会导致这类作品打开后丢失相关积木（与积木连接地相关积木都会受影响），甚至全局报错，无法_正常_编辑，更别说进行修复。就算最好情况只有这个积木消失留下空格，也会给作品的调试带来影响
> 
> 
> 
> 仍然不采用。
> 
> 1. 这个项目是 Beta 版，不是 Release 版，更何况是第一版，我没必要做前向兼容。
> 
> 2. 拖泥带水地删除一个功能只会导致维护问题。
> 
> 3. 好比 Python 2 到 Python 3，干净利落。

关于 Beta 和 Release 的理解可能有些偏差，我们允许功能不完善或者有 bug，但是不能允许存在向前兼容问题。包括官方的一些扩展的迭代都是很谨慎的。

至于 Python 2 到 3 的保守诟病的升级，并不是一个正向案例。

另外 not.js 的命名好像并不适合该 json 处理器（看上去像是一个大而全的 js 框架而这个显然不是），建议换一个更明确的具象的名字。

2023-04-07 10:57 UTC, 9-2-1 commented
> # 更新
> 
>     * 扔掉了 fromBoolean 这个鸡肋功能。
> 
> 
> 没别的了。

![图片](https://user-images.githubusercontent.com/33796749/230597310-0f3af527-5a7d-43bd-8f96-b909ccca352a.png)

fromBoolean 功能不能删除，因为事实证明成员积木不能直接进行判断，话题终结

2023-08-28 07:51 UTC, closed without merging