More_mouse 2.7 修复
Gandi-IDE/custom-extension pull request #88
Opened 2023-06-07 08:41 UTC by little-starts

fix(block):修复锁定鼠标，文本框下无法检测鼠标按键（按下，点击，双击，滚轮）的BUG

2023-06-07 09:46 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
这是为啥？

2023-06-07 09:46 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +		document.addEventListener('mousedown', (e) => {
1. 这个修改为啥？
2. 如果这个修改有其确切的目的，为什么只有 mousedown 这个事件改了？

2023-06-07 09:46 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +		document.addEventListener('click', () => {
问题同上

2023-06-07 09:46 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +		document.addEventListener('dblclick', () => {
问题同上

2023-06-07 09:46 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +		document.addEventListener(
问题同上

2023-06-07 10:39 UTC, little-starts commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
input为了不被官方的js刷新掉，使用了cvs的三个父元素，所以这个地方修改为doc是为了在input上检测
第二个原因，锁定鼠标后鼠标被固定在body下，如果只检测cvs或cvs父元素，在锁定鼠标时无法检测到鼠标事件

2023-06-07 10:40 UTC, little-starts commented on wit_cat/More_Mouse.js
> +		document.addEventListener('mousedown', (e) => {
见上面的第二条

2023-06-07 10:40 UTC, little-starts commented on wit_cat/More_Mouse.js
> +		document.addEventListener('click', () => {
同上

2023-06-07 10:40 UTC, little-starts commented on wit_cat/More_Mouse.js
> +		document.addEventListener('dblclick', () => {
同上

2023-06-07 10:40 UTC, little-starts commented on wit_cat/More_Mouse.js
> +		document.addEventListener(
同上

2023-06-07 10:54 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +		document.addEventListener('mousedown', (e) => {
那为什么只有 mousedown 改了，其他还有很多事件有没有改到 ‘ document’ 下，还是在 canvas 下

2023-06-07 10:55 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
为什么一定要是第三个父元素？第三个父元素一定存在吗，在任意页面中？

2023-06-07 11:43 UTC, little-starts commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
因为前两个元素都存在被官方复写的可能

2023-06-07 11:44 UTC, little-starts commented on wit_cat/More_Mouse.js
> +		document.addEventListener('mousedown', (e) => {
改了的都是电脑操作，没改的都是手机操作，因为手机的鼠标不可能被锁定，所以并没有考虑鼠标被锁定的情况

2023-06-07 14:47 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
两个问题
1. 第三个父元素有没有可能不存在，如果我们修改了 scratch 舞台区的外部页面结果，比如我们出了个只有舞台的页面？
2. 凭什么认为第三个父元素就没有被刷新的可能？

这里感觉你在依赖一个你完全不能控制的，也不能预期的外部数据来作为你功能的核心。
那你的这个扩展就和别的根本和扩展没关系的业务有高度的耦合，比如我们就不能随意的更新 UI 了，不然你的扩展就又挂了。

2023-06-07 14:55 UTC, little-starts commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
1.保证详情页运行无bug，若有问题会提醒用户跳转。
且三层div并没有离开变量监视器的范围，变量也是在这一层。除非你们在更新的页面中舍弃掉原版的变量监视器

2023-06-07 14:56 UTC, little-starts commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
2.第三个元素是纯div
没有id，没有class，且我运行作品并没有观察到任何修改

2023-06-07 15:05 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
> 舍弃掉原版的变量监视器

这个是有计划的

2023-06-08 07:10 UTC, little-starts commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
> 为什么一定要是第三个父元素？
说错了，其实是第一个父元素

2023-06-08 07:11 UTC, little-starts commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
也就是说，就算只有一个cvs，除非你得网页没有body，和cvs是同层级的，哪怕他在body下没有任何父元素也不会有问题

2023-06-08 10:27 UTC, 9-2-1 commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
> 两个问题
> 
>     1. 第三个父元素有没有可能不存在，如果我们修改了 scratch 舞台区的外部页面结果，比如我们出了个只有舞台的页面？
> 
>     2. 凭什么认为第三个父元素就没有被刷新的可能？
> 
> 
> 这里感觉你在依赖一个你完全不能控制的，也不能预期的外部数据来作为你功能的核心。 那你的这个扩展就和别的根本和扩展没关系的业务有高度的耦合，比如我们就不能随意的更新 UI 了，不然你的扩展就又挂了。

难以解释的代码往往来自于难以解决的问题。如果扩展开发工具能够提供一个稳定的用来创建这个附加 div 的函数，问题将很容易被解决。

2023-06-08 10:33 UTC, 9-2-1 commented on wit_cat/More_Mouse.js
> +});
看起来这是个意外？

2023-06-08 10:33 UTC, 9-2-1 requested changes

2023-06-08 10:33 UTC, 9-2-1 commented on wit_cat/More_Mouse.js
> +});
看起来这是个意外？

2023-06-08 10:51 UTC, little-starts commented on wit_cat/More_Mouse.js
> +});
我脑袋烧了，等我晚上回寝室修一下

2023-06-09 10:01 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
ok，一个 parent 我能接受。

2023-06-09 10:04 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +					return canvas.parentNode.parentNode.parentNode;
> 



> > 两个问题
> > ```
> > 1. 第三个父元素有没有可能不存在，如果我们修改了 scratch 舞台区的外部页面结果，比如我们出了个只有舞台的页面？
> > 
> > 2. 凭什么认为第三个父元素就没有被刷新的可能？
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这里感觉你在依赖一个你完全不能控制的，也不能预期的外部数据来作为你功能的核心。 那你的这个扩展就和别的根本和扩展没关系的业务有高度的耦合，比如我们就不能随意的更新 UI 了，不然你的扩展就又挂了。
> 
> 难以解释的代码往往来自于难以解决的问题。如果扩展开发工具能够提供一个稳定的用来创建这个附加 div 的函数，问题将很容易被解决。

附加 dom 这种工具，其实原则上不应该允许。
站在 runtime 的立场上， scr 的 UI 或者 render 只应该是 canvas 内。也就是创作者能够操作的空间应该是代码在 runtime 这个 sandbox 中，UI 在 canvas 这个 sandbox 中。不然漏洞都会比较多。

2023-06-12 05:16 UTC, sylarhcn commented on wit_cat/More_Mouse.js
> +});
所以这个修复了吗？

2023-06-12 06:26 UTC, merged